services:
  postgres:
    image: postgres:17-alpine
    container_name: mtgdle_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
