### BULK DATA
GET {{scryfallHost}}/bulk-data

### BULK DATA DEFAULT CARDS
GET {{scryfallHost}}/bulk-data/default-cards


### SET ALL
GET {{scryfallHost}}/sets

### SET ID
GET {{scryfallHost}}/sets/f7aa47c6-c1e2-4de5-9a68-4406d84bd6bb

### SET CODE
@set_code=prm
GET {{scryfallHost}}/sets/{{set_code}}

### RANDOM
GET {{scryfallHost}}/cards/random


### TEST ID
@card_id=0000a54c-a511-4925-92dc-01b937f9afad
GET {{scryfallHost}}/cards/{{card_id}}

### ID SPLIT
@card_id_split=4bb07091-86d6-4735-82b6-6e71e26710f4
GET {{scryfallHost}}/cards/{{card_id_split}}

### ID FLIP
@card_id_flip=6ee6cd34-c117-4d7e-97d1-8f8464bfaac8
GET {{scryfallHost}}/cards/{{card_id_flip}}

### ID ADVENTURE
@card_id_adventure=b5b71cd2-de35-451f-b16e-2e3936169407
GET {{scryfallHost}}/cards/{{card_id_adventure}}

### ID TRANSFORM
@card_id_transform=70b2cdc5-35b9-443d-b499-c8b75c0d0a64
GET {{scryfallHost}}/cards/{{card_id_transform}}

### ID MODAL_DFC
@card_id_modal_dfc=44657ab1-0a6a-4a5f-9688-86f239083821
GET {{scryfallHost}}/cards/{{card_id_modal_dfc}}

### ID DOUBLE FACE TOKEN
@card_id_double_face_token=0fd5b9c3-9c18-446d-9d81-7a3a90d7bbee
GET {{scryfallHost}}/cards/{{card_id_double_face_token}}

### ID ART SERIES
@card_id_ART_SERIES=8de2ff37-fdb7-4f77-9d48-e99afac9a79e
GET {{scryfallHost}}/cards/{{card_id_ART_SERIES}}

### ID REVERSIBLE
@card_id_reversible=087c3a0d-c710-4451-989e-596b55352184
GET {{scryfallHost}}/cards/{{card_id_reversible}}

### ID NORMALE
@card_id_normale=f57fd4c9-0004-4f71-a30f-2720943f57ca
GET {{scryfallHost}}/cards/{{card_id_normale}}

### PARSE MANA
@manaCost={2}{R} // {1}{R}
GET {{scryfallHost}}/symbology/parse-mana?cost={{manaCost}}

### SEARCH
@q="black%20lotus"
GET {{scryfallHost}}/cards/search?q={{q}}

### SYMBOLOGY
GET {{scryfallHost}}/symbology

### CARD NAME
GET {{scryfallHost}}/catalog/card-names

### NAMED DUAL CARD
GET {{scryfallHost}}/cards/named?fuzzy=Odds+and+Ends

### NAMED SINGLE CARD
GET {{scryfallHost}}/cards/named?fuzzy=bonecrusher+giant

GET {{localhost}}//card/get-by-scryfall-id/{id}?id=f57fd4c9-0004-4f71-a30f-2720943f57ca
